# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.17.1]

    steps:
    - uses: actions/checkout@v2
    - name: Print release version
      run: | 
        echo This is the actual version \'$RELEASE_VERSION\'
        echo `git describe --tags`
        RELEASE_VERSION=`git describe --tags`
        echo This is the actual version \'$RELEASE_VERSION\'
      env:
        RELEASE_VERSION: unversioned
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci --ignore-scripts
    - run: npm run coverage
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # RELEASE_VERSION: ${{ env.RELEASE_VERSION }}